version: "3"

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        ports:
            - "${DATABASE_PORT}:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}

volumes:
    db_data:
